"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var validators_1 = require("./validators/validators");
var email = 'abhishekpoojara@gmail.com';
var zipCode = '360005';
var validator = new validators_1.ValidatorCLS();
var resultOfEmailValidate = validator.isValidEmailStr(email);
var resultOfZipCodeValidate = validator.isValidZipCode(zipCode);
console.log("Valid Email Id OR Not: " + resultOfEmailValidate);
console.log("Valid Zip Code OR Not: " + resultOfZipCodeValidate);
